name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # To fetch all history for all branches and tags. (Will be required for caching with lerna: https://github.com/markuplint/markuplint/pull/111)

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # - name: Build
      #   shell: bash
      #   run: |
      #     yarn --skip-integrity-check --network-timeout 100000
      #     npx electron-replace-ffmpeg
      #     npx electron-codecs-test
      #     ./scripts/check_git_status.sh
      #   env:
      #     NODE_OPTIONS: --max_old_space_size=4096
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9

      # - name: Test (headless)
      #   if: matrix.tests != 'skip'
      #   shell: bash
      #   run: |
      #     yarn test:theia

      # - name: Test (browser)
      #   uses: GabrielBB/xvfb-action@v1
      #   with:
      #     run: yarn test:browser

      # - name: Test (electron)
      #   uses: GabrielBB/xvfb-action@v1
      #   with:
      #     run: yarn test:electron

      # - name: Pre-Publish
      #   run: |
      #     yarn --skip-integrity-check --network-timeout 100000
      #     yarn docs
      #   env:
      #     NODE_OPTIONS: --max_old_space_size=4096
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9

      # - name: Publish NPM
      #   uses: nick-invision/retry@v2
      #   with:
      #     timeout_minutes: 5
      #     retry_wait_seconds: 30
      #     max_attempts: 3
      #     retry_on: error
      #     command: yarn publish:next
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # The variable name comes from here: https://github.com/actions/setup-node/blob/70b9252472eee7495c93bb1588261539c3c2b98d/src/authutil.ts#L48

      - name: Publish NPM (latest)
        id: publish-latest
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          retry_wait_seconds: 30
          max_attempts: 3
          retry_on: error
          # command: yarn publish:latest:minor
          command: touch a.txt && git add . && git commit -m test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # The variable name comes from here: https://github.com/actions/setup-node/blob/70b9252472eee7495c93bb1588261539c3c2b98d/src/authutil.ts#L48

      - name: Push minor version bump
        if: steps.publish-latest.outcome == 'success'
        run: |
          git push -f origin HEAD:v$(node -p "require('./packages/core/package.json').version")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9

      # - name: Publish GH Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./gh-pages
